//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinnitusTrioRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorDetail
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string ZipCode { get; set; }
        public string phone { get; set; }
        public string mobileno { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string uniqueId { get; set; }
        public string HospitalNme { get; set; }
        public string appdemodate { get; set; }
        public Nullable<bool> useragreementGenerated { get; set; }
        public bool Isactive { get; set; }
        public string DoctorCode { get; set; }
        public string password { get; set; }
        public Nullable<int> pin { get; set; }
        public Nullable<bool> isFirstLogin { get; set; }
        public Nullable<int> SubscriptionType { get; set; }
        public Nullable<System.DateTime> SubscriptionDate { get; set; }
    }
}
