//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinnitusTrioRequest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TinnitusTrioEntities : DbContext
    {
        public TinnitusTrioEntities()
            : base("name=TinnitusTrioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OfflineLicenseRequest> OfflineLicenseRequests { get; set; }
        public virtual DbSet<DoctorDetail> DoctorDetails { get; set; }
    }
}
