//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinnitusTrioRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfflineLicenseRequest
    {
        public int requestId { get; set; }
        public string doctorCode { get; set; }
        public Nullable<bool> requestActiveStatus { get; set; }
        public string remarks { get; set; }
        public Nullable<int> licenseQuantity { get; set; }
        public Nullable<System.DateTime> requestdate { get; set; }
        public Nullable<System.DateTime> requestenddate { get; set; }
        public Nullable<bool> requestisserviced { get; set; }
    }
}
