//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_Employee
    {
        public admin_Employee()
        {
            this.UserRoleMappings = new HashSet<UserRoleMapping>();
        }
    
        public int Employeeid { get; set; }
        public string userid { get; set; }
        public string password { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public string addressline1 { get; set; }
        public string addressline2 { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string pincode { get; set; }
        public string telephone { get; set; }
        public string mobileno { get; set; }
        public string emailaddress { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public Nullable<bool> isSuperAdmin { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public string Field5 { get; set; }
        public Nullable<bool> isFirstLogin { get; set; }
    
        public virtual ICollection<UserRoleMapping> UserRoleMappings { get; set; }
    }
}
