//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPINSTALLERLOG
    {
        public int id { get; set; }
        public string installDoctorId { get; set; }
        public string installDoctorName { get; set; }
        public string installPatientid { get; set; }
        public Nullable<System.DateTime> AppinstallDate { get; set; }
        public string InstalledAppName { get; set; }
    }
}
