//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMMLogger
    {
        public int id { get; set; }
        public string PatientId { get; set; }
        public string LogDate { get; set; }
        public string LogTime { get; set; }
        public string Track { get; set; }
        public string Duration { get; set; }
        public string isActive { get; set; }
        public string isSync { get; set; }
        public Nullable<System.DateTime> SyncDateTimeStamp { get; set; }
    }
}
