//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMTLOGGER
    {
        public int LOGID { get; set; }
        public string PATIENTID { get; set; }
        public string LOGDATE { get; set; }
        public string LOGTIME { get; set; }
        public string DURATION { get; set; }
        public string ISACTIVE { get; set; }
        public string ISSYNC { get; set; }
        public System.DateTime SyncDateTimeStamp { get; set; }
    }
}
