//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMTSetFrequency
    {
        public int Id { get; set; }
        public string patientid { get; set; }
        public string Frequency { get; set; }
        public System.DateTime SetDateTime { get; set; }
        public bool isActive { get; set; }
    }
}
