//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TinnitusTrioEntities : DbContext
    {
        public TinnitusTrioEntities()
            : base("name=TinnitusTrioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPINSTALLERLOG> APPINSTALLERLOGs { get; set; }
        public virtual DbSet<CMESLogger> CMESLoggers { get; set; }
        public virtual DbSet<CMMLogger> CMMLoggers { get; set; }
        public virtual DbSet<CMNLogger> CMNLoggers { get; set; }
        public virtual DbSet<CMTLOGGER> CMTLOGGERs { get; set; }
        public virtual DbSet<CMTSetFrequency> CMTSetFrequencies { get; set; }
        public virtual DbSet<DoctorDetail> DoctorDetails { get; set; }
        public virtual DbSet<FrequencyInstallerLog> FrequencyInstallerLogs { get; set; }
        public virtual DbSet<PatientRegistration> PatientRegistrations { get; set; }
        public virtual DbSet<uniqueID> uniqueIDs { get; set; }
        public virtual DbSet<SerialNumber> SerialNumbers { get; set; }
        public virtual DbSet<userauthentication> userauthentications { get; set; }
        public virtual DbSet<OfflineLicenseRequest> OfflineLicenseRequests { get; set; }
        public virtual DbSet<OFFLINELICENSESTRACKER> OFFLINELICENSESTRACKERs { get; set; }
        public virtual DbSet<admin_Employee> admin_Employee { get; set; }
        public virtual DbSet<MenuList> MenuLists { get; set; }
        public virtual DbSet<RoleMenuMapping> RoleMenuMappings { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserRoleMapping> UserRoleMappings { get; set; }
    
        public virtual int ActivateApps(string appName, string pATIENTID)
        {
            var appNameParameter = appName != null ?
                new ObjectParameter("AppName", appName) :
                new ObjectParameter("AppName", typeof(string));
    
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActivateApps", appNameParameter, pATIENTIDParameter);
        }
    
        public virtual ObjectResult<APPINSTALLHISTORY_Result> APPINSTALLHISTORY(string patientid, Nullable<int> doctorid, Nullable<System.DateTime> indate, Nullable<System.DateTime> outdate, string flg)
        {
            var patientidParameter = patientid != null ?
                new ObjectParameter("patientid", patientid) :
                new ObjectParameter("patientid", typeof(string));
    
            var doctoridParameter = doctorid.HasValue ?
                new ObjectParameter("doctorid", doctorid) :
                new ObjectParameter("doctorid", typeof(int));
    
            var indateParameter = indate.HasValue ?
                new ObjectParameter("indate", indate) :
                new ObjectParameter("indate", typeof(System.DateTime));
    
            var outdateParameter = outdate.HasValue ?
                new ObjectParameter("outdate", outdate) :
                new ObjectParameter("outdate", typeof(System.DateTime));
    
            var flgParameter = flg != null ?
                new ObjectParameter("flg", flg) :
                new ObjectParameter("flg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APPINSTALLHISTORY_Result>("APPINSTALLHISTORY", patientidParameter, doctoridParameter, indateParameter, outdateParameter, flgParameter);
        }
    
        public virtual ObjectResult<APPINSTALLHISTORYWILDCARD_Result> APPINSTALLHISTORYWILDCARD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APPINSTALLHISTORYWILDCARD_Result>("APPINSTALLHISTORYWILDCARD");
        }
    
        public virtual ObjectResult<appinstallhistoryWithoutDoctorId_Result> appinstallhistoryWithoutDoctorId(string flag, Nullable<System.DateTime> intime, Nullable<System.DateTime> outtime)
        {
            var flagParameter = flag != null ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(string));
    
            var intimeParameter = intime.HasValue ?
                new ObjectParameter("intime", intime) :
                new ObjectParameter("intime", typeof(System.DateTime));
    
            var outtimeParameter = outtime.HasValue ?
                new ObjectParameter("outtime", outtime) :
                new ObjectParameter("outtime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<appinstallhistoryWithoutDoctorId_Result>("appinstallhistoryWithoutDoctorId", flagParameter, intimeParameter, outtimeParameter);
        }
    
        public virtual ObjectResult<string> AppInstallLogger(string installDoctorId, string installDoctorName, string installPatientid, string installedAppName)
        {
            var installDoctorIdParameter = installDoctorId != null ?
                new ObjectParameter("installDoctorId", installDoctorId) :
                new ObjectParameter("installDoctorId", typeof(string));
    
            var installDoctorNameParameter = installDoctorName != null ?
                new ObjectParameter("installDoctorName", installDoctorName) :
                new ObjectParameter("installDoctorName", typeof(string));
    
            var installPatientidParameter = installPatientid != null ?
                new ObjectParameter("installPatientid", installPatientid) :
                new ObjectParameter("installPatientid", typeof(string));
    
            var installedAppNameParameter = installedAppName != null ?
                new ObjectParameter("InstalledAppName", installedAppName) :
                new ObjectParameter("InstalledAppName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AppInstallLogger", installDoctorIdParameter, installDoctorNameParameter, installPatientidParameter, installedAppNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> AuthUser(Nullable<int> uniqueID, string macid, string serialno, string hashid)
        {
            var uniqueIDParameter = uniqueID.HasValue ?
                new ObjectParameter("uniqueID", uniqueID) :
                new ObjectParameter("uniqueID", typeof(int));
    
            var macidParameter = macid != null ?
                new ObjectParameter("macid", macid) :
                new ObjectParameter("macid", typeof(string));
    
            var serialnoParameter = serialno != null ?
                new ObjectParameter("serialno", serialno) :
                new ObjectParameter("serialno", typeof(string));
    
            var hashidParameter = hashid != null ?
                new ObjectParameter("hashid", hashid) :
                new ObjectParameter("hashid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("AuthUser", uniqueIDParameter, macidParameter, serialnoParameter, hashidParameter);
        }
    
        public virtual ObjectResult<string> checkActiveStatus(string uniqueid)
        {
            var uniqueidParameter = uniqueid != null ?
                new ObjectParameter("uniqueid", uniqueid) :
                new ObjectParameter("uniqueid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("checkActiveStatus", uniqueidParameter);
        }
    
        public virtual ObjectResult<string> CheckActiveStatusDoctor(string doctorid)
        {
            var doctoridParameter = doctorid != null ?
                new ObjectParameter("doctorid", doctorid) :
                new ObjectParameter("doctorid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CheckActiveStatusDoctor", doctoridParameter);
        }
    
        public virtual ObjectResult<string> CHECKISFIRSTLOGIN(Nullable<int> doctorid)
        {
            var doctoridParameter = doctorid.HasValue ?
                new ObjectParameter("doctorid", doctorid) :
                new ObjectParameter("doctorid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CHECKISFIRSTLOGIN", doctoridParameter);
        }
    
        public virtual ObjectResult<DeActivateApps_Result> DeActivateApps(string appName, string pATIENTID)
        {
            var appNameParameter = appName != null ?
                new ObjectParameter("AppName", appName) :
                new ObjectParameter("AppName", typeof(string));
    
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DeActivateApps_Result>("DeActivateApps", appNameParameter, pATIENTIDParameter);
        }
    
        public virtual ObjectResult<fetchDoctorDetails_Result> fetchDoctorDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fetchDoctorDetails_Result>("fetchDoctorDetails");
        }
    
        public virtual ObjectResult<string> FreqInstallerLogger(string installDoctorId, string installDoctorName, string installPatientid, string installedFreqValue)
        {
            var installDoctorIdParameter = installDoctorId != null ?
                new ObjectParameter("installDoctorId", installDoctorId) :
                new ObjectParameter("installDoctorId", typeof(string));
    
            var installDoctorNameParameter = installDoctorName != null ?
                new ObjectParameter("installDoctorName", installDoctorName) :
                new ObjectParameter("installDoctorName", typeof(string));
    
            var installPatientidParameter = installPatientid != null ?
                new ObjectParameter("installPatientid", installPatientid) :
                new ObjectParameter("installPatientid", typeof(string));
    
            var installedFreqValueParameter = installedFreqValue != null ?
                new ObjectParameter("InstalledFreqValue", installedFreqValue) :
                new ObjectParameter("InstalledFreqValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("FreqInstallerLogger", installDoctorIdParameter, installDoctorNameParameter, installPatientidParameter, installedFreqValueParameter);
        }
    
        public virtual ObjectResult<FREQINSTALLHISTORY_Result> FREQINSTALLHISTORY(string patientid, Nullable<int> doctorid, Nullable<System.DateTime> indate, Nullable<System.DateTime> outdate, string flg)
        {
            var patientidParameter = patientid != null ?
                new ObjectParameter("patientid", patientid) :
                new ObjectParameter("patientid", typeof(string));
    
            var doctoridParameter = doctorid.HasValue ?
                new ObjectParameter("doctorid", doctorid) :
                new ObjectParameter("doctorid", typeof(int));
    
            var indateParameter = indate.HasValue ?
                new ObjectParameter("indate", indate) :
                new ObjectParameter("indate", typeof(System.DateTime));
    
            var outdateParameter = outdate.HasValue ?
                new ObjectParameter("outdate", outdate) :
                new ObjectParameter("outdate", typeof(System.DateTime));
    
            var flgParameter = flg != null ?
                new ObjectParameter("flg", flg) :
                new ObjectParameter("flg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FREQINSTALLHISTORY_Result>("FREQINSTALLHISTORY", patientidParameter, doctoridParameter, indateParameter, outdateParameter, flgParameter);
        }
    
        public virtual ObjectResult<GenerateCmesReport_Result> GenerateCmesReport(string pATIENTID)
        {
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenerateCmesReport_Result>("GenerateCmesReport", pATIENTIDParameter);
        }
    
        public virtual ObjectResult<GenerateCmesReportDateWise_Result> GenerateCmesReportDateWise(string pATIENTID, Nullable<System.DateTime> indate, Nullable<System.DateTime> outdate)
        {
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            var indateParameter = indate.HasValue ?
                new ObjectParameter("indate", indate) :
                new ObjectParameter("indate", typeof(System.DateTime));
    
            var outdateParameter = outdate.HasValue ?
                new ObjectParameter("outdate", outdate) :
                new ObjectParameter("outdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenerateCmesReportDateWise_Result>("GenerateCmesReportDateWise", pATIENTIDParameter, indateParameter, outdateParameter);
        }
    
        public virtual ObjectResult<GenerateCmmReport_Result> GenerateCmmReport(string pATIENTID)
        {
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenerateCmmReport_Result>("GenerateCmmReport", pATIENTIDParameter);
        }
    
        public virtual ObjectResult<GenerateCmmReportDateWise_Result> GenerateCmmReportDateWise(string pATIENTID, Nullable<System.DateTime> indate, Nullable<System.DateTime> outdate)
        {
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            var indateParameter = indate.HasValue ?
                new ObjectParameter("indate", indate) :
                new ObjectParameter("indate", typeof(System.DateTime));
    
            var outdateParameter = outdate.HasValue ?
                new ObjectParameter("outdate", outdate) :
                new ObjectParameter("outdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenerateCmmReportDateWise_Result>("GenerateCmmReportDateWise", pATIENTIDParameter, indateParameter, outdateParameter);
        }
    
        public virtual ObjectResult<GenerateCmnReport_Result> GenerateCmnReport(string pATIENTID)
        {
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenerateCmnReport_Result>("GenerateCmnReport", pATIENTIDParameter);
        }
    
        public virtual ObjectResult<GenerateCmnReportDateWise_Result> GenerateCmnReportDateWise(string pATIENTID, Nullable<System.DateTime> indate, Nullable<System.DateTime> outdate)
        {
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            var indateParameter = indate.HasValue ?
                new ObjectParameter("indate", indate) :
                new ObjectParameter("indate", typeof(System.DateTime));
    
            var outdateParameter = outdate.HasValue ?
                new ObjectParameter("outdate", outdate) :
                new ObjectParameter("outdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenerateCmnReportDateWise_Result>("GenerateCmnReportDateWise", pATIENTIDParameter, indateParameter, outdateParameter);
        }
    
        public virtual ObjectResult<GenerateCmtReport_Result> GenerateCmtReport(string pATIENTID)
        {
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenerateCmtReport_Result>("GenerateCmtReport", pATIENTIDParameter);
        }
    
        public virtual ObjectResult<GenerateCmtReportDateWise_Result> GenerateCmtReportDateWise(string pATIENTID, Nullable<System.DateTime> indate, Nullable<System.DateTime> outdate)
        {
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            var indateParameter = indate.HasValue ?
                new ObjectParameter("indate", indate) :
                new ObjectParameter("indate", typeof(System.DateTime));
    
            var outdateParameter = outdate.HasValue ?
                new ObjectParameter("outdate", outdate) :
                new ObjectParameter("outdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenerateCmtReportDateWise_Result>("GenerateCmtReportDateWise", pATIENTIDParameter, indateParameter, outdateParameter);
        }
    
        public virtual ObjectResult<string> getUniqueID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getUniqueID");
        }
    
        public virtual ObjectResult<string> insertDevicedetails(string uniqueID, string macid, string serialno, string hashString)
        {
            var uniqueIDParameter = uniqueID != null ?
                new ObjectParameter("UniqueID", uniqueID) :
                new ObjectParameter("UniqueID", typeof(string));
    
            var macidParameter = macid != null ?
                new ObjectParameter("macid", macid) :
                new ObjectParameter("macid", typeof(string));
    
            var serialnoParameter = serialno != null ?
                new ObjectParameter("serialno", serialno) :
                new ObjectParameter("serialno", typeof(string));
    
            var hashStringParameter = hashString != null ?
                new ObjectParameter("hashString", hashString) :
                new ObjectParameter("hashString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("insertDevicedetails", uniqueIDParameter, macidParameter, serialnoParameter, hashStringParameter);
        }
    
        public virtual int InsertFrequencyDetails(string fREQUENCY, string pATIENTID)
        {
            var fREQUENCYParameter = fREQUENCY != null ?
                new ObjectParameter("FREQUENCY", fREQUENCY) :
                new ObjectParameter("FREQUENCY", typeof(string));
    
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertFrequencyDetails", fREQUENCYParameter, pATIENTIDParameter);
        }
    
        public virtual ObjectResult<string> insertPatientDetails(string patientID, string firstname, string middlename, string lastname, string addressline1, string addressline2, string city, string state, string country, string zipcode, string email, string telephone, string mobile, string doctorCode, string uniqueId)
        {
            var patientIDParameter = patientID != null ?
                new ObjectParameter("PatientID", patientID) :
                new ObjectParameter("PatientID", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var middlenameParameter = middlename != null ?
                new ObjectParameter("middlename", middlename) :
                new ObjectParameter("middlename", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var addressline1Parameter = addressline1 != null ?
                new ObjectParameter("addressline1", addressline1) :
                new ObjectParameter("addressline1", typeof(string));
    
            var addressline2Parameter = addressline2 != null ?
                new ObjectParameter("addressline2", addressline2) :
                new ObjectParameter("addressline2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var zipcodeParameter = zipcode != null ?
                new ObjectParameter("zipcode", zipcode) :
                new ObjectParameter("zipcode", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var telephoneParameter = telephone != null ?
                new ObjectParameter("telephone", telephone) :
                new ObjectParameter("telephone", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            var doctorCodeParameter = doctorCode != null ?
                new ObjectParameter("doctorCode", doctorCode) :
                new ObjectParameter("doctorCode", typeof(string));
    
            var uniqueIdParameter = uniqueId != null ?
                new ObjectParameter("UniqueId", uniqueId) :
                new ObjectParameter("UniqueId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("insertPatientDetails", patientIDParameter, firstnameParameter, middlenameParameter, lastnameParameter, addressline1Parameter, addressline2Parameter, cityParameter, stateParameter, countryParameter, zipcodeParameter, emailParameter, telephoneParameter, mobileParameter, doctorCodeParameter, uniqueIdParameter);
        }
    
        public virtual ObjectResult<string> LoginDoctor(string loginid, Nullable<int> doctorid, string password, string pin)
        {
            var loginidParameter = loginid != null ?
                new ObjectParameter("loginid", loginid) :
                new ObjectParameter("loginid", typeof(string));
    
            var doctoridParameter = doctorid.HasValue ?
                new ObjectParameter("doctorid", doctorid) :
                new ObjectParameter("doctorid", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var pinParameter = pin != null ?
                new ObjectParameter("pin", pin) :
                new ObjectParameter("pin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("LoginDoctor", loginidParameter, doctoridParameter, passwordParameter, pinParameter);
        }
    
        public virtual ObjectResult<serialValidation_Result> serialValidation(string serial1, string serial2, string serial3, string serial4, string serial5, string doctorID)
        {
            var serial1Parameter = serial1 != null ?
                new ObjectParameter("serial1", serial1) :
                new ObjectParameter("serial1", typeof(string));
    
            var serial2Parameter = serial2 != null ?
                new ObjectParameter("serial2", serial2) :
                new ObjectParameter("serial2", typeof(string));
    
            var serial3Parameter = serial3 != null ?
                new ObjectParameter("serial3", serial3) :
                new ObjectParameter("serial3", typeof(string));
    
            var serial4Parameter = serial4 != null ?
                new ObjectParameter("serial4", serial4) :
                new ObjectParameter("serial4", typeof(string));
    
            var serial5Parameter = serial5 != null ?
                new ObjectParameter("serial5", serial5) :
                new ObjectParameter("serial5", typeof(string));
    
            var doctorIDParameter = doctorID != null ?
                new ObjectParameter("DoctorID", doctorID) :
                new ObjectParameter("DoctorID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<serialValidation_Result>("serialValidation", serial1Parameter, serial2Parameter, serial3Parameter, serial4Parameter, serial5Parameter, doctorIDParameter);
        }
    
        public virtual ObjectResult<string> spAdminDetails(string aDMINID, string pIN)
        {
            var aDMINIDParameter = aDMINID != null ?
                new ObjectParameter("ADMINID", aDMINID) :
                new ObjectParameter("ADMINID", typeof(string));
    
            var pINParameter = pIN != null ?
                new ObjectParameter("PIN", pIN) :
                new ObjectParameter("PIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spAdminDetails", aDMINIDParameter, pINParameter);
        }
    
        public virtual ObjectResult<string> spAdminUpdatePasswordDetails(string aDMINID, string pIN, string password)
        {
            var aDMINIDParameter = aDMINID != null ?
                new ObjectParameter("ADMINID", aDMINID) :
                new ObjectParameter("ADMINID", typeof(string));
    
            var pINParameter = pIN != null ?
                new ObjectParameter("PIN", pIN) :
                new ObjectParameter("PIN", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spAdminUpdatePasswordDetails", aDMINIDParameter, pINParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> spCheckActivationStatusDoctoronDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spCheckActivationStatusDoctoronDate");
        }
    
        public virtual ObjectResult<string> spCreateDoctor(string firstName, string middleName, string lastName, string address1, string address2, string country, string state, string city, string zipCode, string phone, string mobile, string fax, string email, string website, string hospitalName, string doctorCode, Nullable<int> subscriptionType, Nullable<System.DateTime> subscriptionDate, string gUID1, string gUID2, string gUID3, string gUID4, string gUID5)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("Address1", address1) :
                new ObjectParameter("Address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("Address2", address2) :
                new ObjectParameter("Address2", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var zipCodeParameter = zipCode != null ?
                new ObjectParameter("ZipCode", zipCode) :
                new ObjectParameter("ZipCode", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("Fax", fax) :
                new ObjectParameter("Fax", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var websiteParameter = website != null ?
                new ObjectParameter("Website", website) :
                new ObjectParameter("Website", typeof(string));
    
            var hospitalNameParameter = hospitalName != null ?
                new ObjectParameter("HospitalName", hospitalName) :
                new ObjectParameter("HospitalName", typeof(string));
    
            var doctorCodeParameter = doctorCode != null ?
                new ObjectParameter("DoctorCode", doctorCode) :
                new ObjectParameter("DoctorCode", typeof(string));
    
            var subscriptionTypeParameter = subscriptionType.HasValue ?
                new ObjectParameter("SubscriptionType", subscriptionType) :
                new ObjectParameter("SubscriptionType", typeof(int));
    
            var subscriptionDateParameter = subscriptionDate.HasValue ?
                new ObjectParameter("SubscriptionDate", subscriptionDate) :
                new ObjectParameter("SubscriptionDate", typeof(System.DateTime));
    
            var gUID1Parameter = gUID1 != null ?
                new ObjectParameter("GUID1", gUID1) :
                new ObjectParameter("GUID1", typeof(string));
    
            var gUID2Parameter = gUID2 != null ?
                new ObjectParameter("GUID2", gUID2) :
                new ObjectParameter("GUID2", typeof(string));
    
            var gUID3Parameter = gUID3 != null ?
                new ObjectParameter("GUID3", gUID3) :
                new ObjectParameter("GUID3", typeof(string));
    
            var gUID4Parameter = gUID4 != null ?
                new ObjectParameter("GUID4", gUID4) :
                new ObjectParameter("GUID4", typeof(string));
    
            var gUID5Parameter = gUID5 != null ?
                new ObjectParameter("GUID5", gUID5) :
                new ObjectParameter("GUID5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spCreateDoctor", firstNameParameter, middleNameParameter, lastNameParameter, address1Parameter, address2Parameter, countryParameter, stateParameter, cityParameter, zipCodeParameter, phoneParameter, mobileParameter, faxParameter, emailParameter, websiteParameter, hospitalNameParameter, doctorCodeParameter, subscriptionTypeParameter, subscriptionDateParameter, gUID1Parameter, gUID2Parameter, gUID3Parameter, gUID4Parameter, gUID5Parameter);
        }
    
        public virtual ObjectResult<string> spUpdateDoctorSubscription(string doctorid, Nullable<System.DateTime> subscriptiondate)
        {
            var doctoridParameter = doctorid != null ?
                new ObjectParameter("doctorid", doctorid) :
                new ObjectParameter("doctorid", typeof(string));
    
            var subscriptiondateParameter = subscriptiondate.HasValue ?
                new ObjectParameter("subscriptiondate", subscriptiondate) :
                new ObjectParameter("subscriptiondate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spUpdateDoctorSubscription", doctoridParameter, subscriptiondateParameter);
        }
    
        public virtual ObjectResult<string> spUpdateDoctorSubscriptionTypenDate(string doctorid, Nullable<System.DateTime> subscriptiondate, Nullable<int> subscriptionType)
        {
            var doctoridParameter = doctorid != null ?
                new ObjectParameter("doctorid", doctorid) :
                new ObjectParameter("doctorid", typeof(string));
    
            var subscriptiondateParameter = subscriptiondate.HasValue ?
                new ObjectParameter("subscriptiondate", subscriptiondate) :
                new ObjectParameter("subscriptiondate", typeof(System.DateTime));
    
            var subscriptionTypeParameter = subscriptionType.HasValue ?
                new ObjectParameter("subscriptionType", subscriptionType) :
                new ObjectParameter("subscriptionType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spUpdateDoctorSubscriptionTypenDate", doctoridParameter, subscriptiondateParameter, subscriptionTypeParameter);
        }
    
        public virtual ObjectResult<string> UpdateDesktopAppLoginDetails(Nullable<int> userid, string password, string pin, string doctorcode)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var pinParameter = pin != null ?
                new ObjectParameter("pin", pin) :
                new ObjectParameter("pin", typeof(string));
    
            var doctorcodeParameter = doctorcode != null ?
                new ObjectParameter("doctorcode", doctorcode) :
                new ObjectParameter("doctorcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UpdateDesktopAppLoginDetails", useridParameter, passwordParameter, pinParameter, doctorcodeParameter);
        }
    
        public virtual int UpdateLogindetails(string userName, string password, string pin)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var pinParameter = pin != null ?
                new ObjectParameter("Pin", pin) :
                new ObjectParameter("Pin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateLogindetails", userNameParameter, passwordParameter, pinParameter);
        }
    
        public virtual ObjectResult<string> XMLLogSync(string xML, string module)
        {
            var xMLParameter = xML != null ?
                new ObjectParameter("XML", xML) :
                new ObjectParameter("XML", typeof(string));
    
            var moduleParameter = module != null ?
                new ObjectParameter("Module", module) :
                new ObjectParameter("Module", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("XMLLogSync", xMLParameter, moduleParameter);
        }
    }
}
