//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFLINELICENSESTRACKER
    {
        public string DoctorCode { get; set; }
        public Nullable<int> lastSerialNumber { get; set; }
        public Nullable<int> requestId { get; set; }
        public string SerialKey { get; set; }
        public Nullable<bool> isActive { get; set; }
        public int id { get; set; }
    }
}
