//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRegistration
    {
        public int Id { get; set; }
        public string patientID { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public string addressline1 { get; set; }
        public string addressline2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string zipcode { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string mobile { get; set; }
        public bool isActive { get; set; }
        public string referredDoctor { get; set; }
        public bool cmtLoaded { get; set; }
        public bool cmmLoaded { get; set; }
        public bool cmesLoaded { get; set; }
        public bool cmnLoaded { get; set; }
        public bool cmmActive { get; set; }
        public bool cmtActive { get; set; }
        public bool cmnActive { get; set; }
        public bool cmesActive { get; set; }
        public Nullable<bool> SyncActive { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public string Field5 { get; set; }
        public string patientNumber { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public Nullable<System.DateTime> cmtinstallationdate { get; set; }
        public Nullable<System.DateTime> cmminstallationdate { get; set; }
        public Nullable<System.DateTime> cmesinstallationdate { get; set; }
        public Nullable<System.DateTime> cmninstallationdate { get; set; }
    }
}
