//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleMapping
    {
        public int UserRoleMappingId { get; set; }
        public int Roleid { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public string Field5 { get; set; }
    
        public virtual admin_Employee admin_Employee { get; set; }
        public virtual Role Role { get; set; }
    }
}
