//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class userauthentication
    {
        public string userId { get; set; }
        public string macID { get; set; }
        public string serialNo { get; set; }
        public string uniqueString { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
